name: Release

on:
  workflow_run:
    workflows: ["Build & Upload Artifact"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: List all artifacts for this workflow run
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = ${{ github.event.workflow_run.id }};
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id,
            });
            console.log("Artifacts found:", artifacts.data.artifacts.map(a => ({
              id: a.id,
              name: a.name,
              size_in_bytes: a.size_in_bytes,
              expired: a.expired,
              archive_download_url: a.archive_download_url
            })));
            const matchArtifact = artifacts.data.artifacts.find(a => a.name === "proton-anarchy");
            if (!matchArtifact) {
              core.setFailed("Artifact not found");
            } else {
              console.log("Matched artifact:", matchArtifact);
              core.setOutput("artifact_id", matchArtifact.id);
            }
        id: find_artifact

      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: proton-anarchy
          path: ./dist

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get version from Cargo.toml and append run number
        id: get_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n1 | awk -F\" '{print $2}')
          VERSION_WITH_RUN="${VERSION}-${GITHUB_RUN_NUMBER}"
          echo "version=$VERSION_WITH_RUN" >> $GITHUB_OUTPUT

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: ./dist/proton-anarchy
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
