name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build (Release)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: proton-anarchy
          path: target/release/proton-anarchy

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: proton-anarchy
          path: ./dist

      - name: Get version from Cargo.toml and append run number
        id: get_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n1 | awk -F\" '{print $2}')
          VERSION_WITH_RUN="${VERSION}-${GITHUB_RUN_NUMBER}"
          echo "version=$VERSION_WITH_RUN" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: ./dist/proton-anarchy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
